sources:
    - name: EXAM_DB
      schema: STAGING1
      tables:
        - name: EVENT_RESOURCE
          identifier: EVENT_RESOURCE
        - name: WEATHER_RESOURCE
          identifier: WEATHER_RESOURCE