'''
   _____      __                 ____        __         
  / ___/___  / /___  ______     / __ \____  / /__  _____
  \__ \/ _ \/ __/ / / / __ \   / /_/ / __ \/ / _ \/ ___/
 ___/ /  __/ /_/ /_/ / /_/ /  / _, _/ /_/ / /  __(__  ) 
/____/\___/\__/\__,_/ .___/  /_/ |_|\____/_/\___/____/  
                   /_/                                                           
'''
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS ExamDLTRole COMMENT = 'Role for data ingestion.';
CREATE ROLE IF NOT EXISTS ExamDBTRole COMMENT = 'Role for data transformation.';
CREATE ROLE IF NOT EXISTS ExamAnalystRole COMMENT = 'Role for data analysis.';

USE ROLE SECURITYADMIN;


GRANT USAGE ON WAREHOUSE EXAM_WH TO ROLE ExamDLTRole;
GRANT USAGE ON WAREHOUSE EXAM_WH TO ROLE ExamDBTRole;


GRANT USAGE ON DATABASE EXAM_DB TO ROLE ExamDLTRole;
GRANT USAGE ON DATABASE EXAM_DB TO ROLE ExamDBTRole;
GRANT USAGE ON DATABASE EXAM_DB TO ROLE ExamAnalystRole;

--- Granting acces to schemas
GRANT USAGE ON SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;
GRANT USAGE ON SCHEMA EXAM_DB.Staging2 TO ROLE ExamDLTRole;

GRANT USAGE ON SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;
GRANT USAGE ON SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;

GRANT USAGE ON SCHEMA EXAM_DB.WAREHOUSE TO ROLE ExamDBTRole;

GRANT USAGE ON SCHEMA EXAM_DB.Mart1 TO ROLE ExamDBTRole;
GRANT USAGE ON SCHEMA EXAM_DB.Mart2 TO ROLE ExamDBTRole;

GRANT USAGE ON SCHEMA EXAM_DB.Mart1 TO ROLE ExamAnalystRole;
GRANT USAGE ON SCHEMA EXAM_DB.Mart2 TO ROLE ExamAnalystRole;


GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;
GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDLTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDLTRole;

GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;
GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;


GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Warehouse TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Warehouse TO ROLE ExamDBTRole;

GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamDBTRole;

GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamDBTRole;

GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamAnalystRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamAnalystRole;

GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamAnalystRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamAnalystRole;

GRANT CREATE TABLE ON SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;
GRANT CREATE TABLE ON SCHEMA EXAM_DB.Staging2 TO ROLE ExamDLTRole;


GRANT CREATE VIEW ON SCHEMA EXAM_DB.Mart1 TO ROLE ExamDBTRole;
GRANT CREATE VIEW ON SCHEMA EXAM_DB.Mart2 TO ROLE ExamDBTRole;

GRANT CREATE VIEW ON SCHEMA EXAM_DB.WAREHOUSE TO ROLE ExamDBTRole;

GRANT CREATE VIEW ON SCHEMA EXAM_DB.Mart1 TO ROLE ExamAnalystRole;
GRANT CREATE VIEW ON SCHEMA EXAM_DB.Mart2 TO ROLE ExamAnalystRole;


GRANT SELECT ON ALL VIEWS IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamDBTRole;
GRANT SELECT ON ALL VIEWS IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamDBTRole;

GRANT CREATE TABLE ON SCHEMA EXAM_DB.WAREHOUSE TO ROLE ExamDBTRole;

GRANT SELECT ON ALL VIEWS IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamAnalystRole;
GRANT SELECT ON ALL VIEWS IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamAnalystRole;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EXAM_DB.Mart1 TO ROLE ExamAnalystRole;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EXAM_DB.Mart2 TO ROLE ExamAnalystRole;



GRANT INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.STAGING1 TO ROLE ExamDLTRole;

GRANT INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA EXAM_DB.STAGING2 TO ROLE ExamDLTRole;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.STAGING2 TO ROLE ExamDLTRole;


GRANT INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;

GRANT INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;


GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.warehouse TO ROLE ExamDBTRole;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.warehouse TO ROLE ExamDBTRole;


GRANT INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA EXAM_DB.mart1 TO ROLE ExamAnalystRole;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.mart1 TO ROLE ExamAnalystRole;

GRANT INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA EXAM_DB.mart2 TO ROLE ExamAnalystRole;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA EXAM_DB.mart2 TO ROLE ExamAnalystRole;

GRANT MODIFY ON DATABASE EXAM_DB TO ROLE ExamDBTRole;
GRANT MODIFY ON SCHEMA WAREHOUSE TO ROLE ExamDBTRole;


GRANT ROLE ExamDLTRole TO USER KristoferExamUser;
GRANT ROLE ExamDBTRole TO USER KristoferExamUser;
GRANT ROLE ExamAnalystRole TO USER KristoferExamUser;

GRANT ROLE ExamDLTRole TO USER TimExamUser;
GRANT ROLE ExamDBTRole TO USER TimExamUser;
GRANT ROLE ExamAnalystRole TO USER TimExamUser;

USE DATABASE EXAM_DB;
GRANT CREATE TABLE ON SCHEMA STAGING1 TO ROLE ExamDLTRole;
GRANT CREATE TABLE ON SCHEMA STAGING2 TO ROLE ExamDLTRole;


