USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS EXAM_DB;

CREATE WAREHOUSE exam_wh
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for Exam Project';

USE DATABASE EXAM_DB;

USE WAREHOUSE EXAM_WH;

CREATE SCHEMA IF NOT EXISTS Staging1;
CREATE SCHEMA IF NOT EXISTS Staging2;
CREATE SCHEMA IF NOT EXISTS WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS Mart1;
CREATE SCHEMA IF NOT EXISTS Mart2;