USE ROLE USERADMIN;

--- Creating roles
CREATE ROLE IF NOT EXISTS ExamDLTRole COMMENT = 'Role for data ingestion.';
CREATE ROLE IF NOT EXISTS ExamDBTRole COMMENT = 'Role for data transformation.';
CREATE ROLE IF NOT EXISTS ExamAnalystRole COMMENT = 'Role for data analysis.';

USE ROLE SECURITYADMIN;

--- Granting acces to warehouses
GRANT USAGE ON WAREHOUSE EXAM_WH TO ROLE ExamDLTRole;
GRANT USAGE ON WAREHOUSE EXAM_WH TO ROLE ExamDBTRole;

--- Granting acces to databases
GRANT USAGE ON DATABASE EXAM_DB TO ROLE ExamDLTRole;
GRANT USAGE ON DATABASE EXAM_DB TO ROLE ExamDBTRole;
GRANT USAGE ON DATABASE EXAM_DB TO ROLE ExamAnalystRole;

--- Granting acces to schemas
GRANT USAGE ON SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;
GRANT USAGE ON SCHEMA EXAM_DB.Staging2 TO ROLE ExamDLTRole;

GRANT USAGE ON SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;
GRANT USAGE ON SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;

GRANT USAGE ON SCHEMA EXAM_DB.WAREHOUSE TO ROLE ExamDBTRole;

GRANT USAGE ON SCHEMA EXAM_DB.Mart1 TO ROLE ExamDBTRole;
GRANT USAGE ON SCHEMA EXAM_DB.Mart2 TO ROLE ExamDBTRole;

GRANT USAGE ON SCHEMA EXAM_DB.Mart1 TO ROLE ExamAnalystRole;
GRANT USAGE ON SCHEMA EXAM_DB.Mart2 TO ROLE ExamAnalystRole;

--- Granting select to tables
GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;
GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDLTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDLTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDLTRole;

GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;
GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging1 TO ROLE ExamDBTRole;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXAM_DB.Staging2 TO ROLE ExamDBTRole;